---
- hosts: all

  pre_tasks:
    - name: Ensure cron is installed, otherwise tests will fail | Redhat
      package:
        name: cronie
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure cron is installed, otherwise tests will fail | Debian / Ubuntu
      package:
        name: cron
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - role: jgeusebroek.maxmind-geoip
